name: Run soushuba qiandao
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '16 12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BASE_URL_SECRET: ${{ secrets.BASE_URL_SECRET }}
      SOUSHUBA_USERNAME: ${{ secrets.SOUSHUBA_USERNAME }}
      SOUSHUBA_PASSWORD: ${{ secrets.SOUSHUBA_PASSWORD }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python ssb2.py
