name: ssb2
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '43 14 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SOUSHUBA_HOSTNAME: ${{ secrets.SOUSHUBA_HOSTNAME }}
      SOUSHUBA_USERNAME: ${{ secrets.SOUSHUBA_USERNAME }}
      SOUSHUBA_PASSWORD: ${{ secrets.SOUSHUBA_PASSWORD }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Generate random delay seconds
        id: generate_random_delay
        run: |
          import random
          delay_seconds = random.randint(0, 3600)
          echo "::set-output name=delay_seconds::$delay_seconds"

      
      - run: python ssb2.py
